lae/ansible-role-proxmox

.travis.yml, tasks/main.yml
Resolves #11 
NOTE: The original line may be present on existing installations but shouldn't pose much issue (as the block would be placed underneath). If wanted, users can use the following ad-hoc command to clean /etc/hosts from the previous lineinfile task:
ansible -i inventory all -m lineinfile -a "dest=/etc/hosts state=absent regexp="^{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}$"'
(and any become/ask params as needed)
=> Enumerate all cluster hosts and pvelocalhost in a block (closes #11)

README.md, defaults/main.yml, library/proxmox_group.py, library/proxmox_user.py, module_utils/pvesh.py, tasks/main.yml, tests/group_vars/all, tests/test.yml
This adds `proxmox_user` and `proxmox_group` modules for creating and managing users and groups in PVE. It is cluster-aware and will only run once per cluster if being ran with `pve_cluster_enabled` set to yes/True.
These are defined through the role variables `pve_groups` and `pve_users`.
=> Add logic for managing users and groups in PVE

README.md, defaults/main.yml, library/proxmox_acl.py, module_utils/pvesh.py, tasks/main.yml, tests/group_vars/all, tests/test.yml
This adds a `proxmox_acl` module, with similar characteristics to #18. They're defined through `pve_acls`.
=> Add logic for managing ACLs in Proxmox

README.md, defaults/main.yml, tasks/identify_needed_packages.yml, tasks/main.yml, tests/group_vars/all
This introduces a variable to set to install ZFS packages and any extra packages, as well as reorganizes some tasks. It allows an email to be configured to receive events from the ZFS module. It also removes installation of `python-pip` (as this role does not install `proxmoxer` anymore, and it adds to the installation time).
=> ZFS and extra package installation

README.md, defaults/main.yml, tasks/main.yml
sometimes dist upgrade operation can be dangerous.
so would nice to set otherwise.
ps: it's enabled by default
=> Allow upgrade step to be configurable

tasks/ssh_cluster_config.yml, vars/debian-jessie.yml, vars/debian-stretch.yml
To my knowledge, there's no need to allow password authentication.
Btw, thanks for the great role. I'm just starting to use it :)
=> Limit root login between PVE cluster hosts to key authentication

README.md, defaults/main.yml, tasks/main.yml, tasks/ssl_letsencrypt.yml, templates/pve-letsencrypt-post-hook.sh.j2
This PR adds new tasks to obtain and install Let's Encrypt SSL certificates for pveproxy using the external role [systemli.letsencrypt](https://galaxy.ansible.com/systemli/letsencrypt/).
=> Let's Encrypt SSL certificate support

README.md, tasks/disable_nmi_watchdog.yml, tasks/ipmi_watchdog.yml, tasks/kernel_module_cleanup.yml, tasks/main.yml
Switch all includes to import_tasks or include_tasks
Update filter tests
Replace 'unsafe' args for ACL management
=> Fix deprecation warnings for Ansible 2.6

module_utils/pvesh.py
There was a little change in output of pvesh in august (no 200 status line in result when OK + default json export changed to pretty tables) which needs to be reflected in pvesh ansible module.
=> Update pvesh module_util to reflect upstream changes

tasks/identify_needed_packages.yml
Hard-coding an MTA to install prevents users of this role from using an
alternative MTA of their choice.
While an MTA is required to use Proxmox VE there is already a dependency
on the mail-transport-agent meta-package in the Proxmox packages which
ensures that this requirement is satisfied. Leave the choice of which MTA
to use to the user and don't hard-code it in this role.
=> Don't install postfix

README.md, defaults/main.yml, tasks/ceph.yml, vars/debian-buster.yml, vars/debian-stretch.yml
Current implementation of ceph is not working with proxmox 6.x because the repository is different (nautilus instead of luminous). Another problem is with the ceph service, the used template under  /usr/share/doc/pve-manager/examples/ceph.service does not exist in proxmox 6.x. Maybe there has to be another fix (I do not know the purpose for this service, proxmox is starting the services well).
=> Add different ceph repository for proxmox 6.x

README.md, defaults/main.yml, tasks/ssh_cluster_config.yml
If the SSH port on the hosts is not the default port, then joining a Cluster with -use-ssh will never work. With the new variable pve_ssh_port it is possible to set the specific port. It will be written to /etc/ssh/ssh_config which is already changed by hostkey assignment and it makes sense to change the default port there too.
=> Allow SSH port for cluster hosts to be configurable

.gitignore, .travis.yml, README.md, defaults/main.yml, tasks/ceph.yml, tasks/identify_needed_packages.yml, tasks/main.yml, tests/ansible.cfg, tests/group_vars/all, tests/install.yml, vars/debian-buster.yml, vars/debian-stretch.yml
- Enabled Ceph in tests so that we have some basic testing, but anything that requires OSDs is skipped.
- Moved Ceph package installation to the main package install task to fix an idempotency issue.
- Several tasks just needed to be run on a single monitor host, so I moved those into conditional blocks (as well as prefixed internally used variables with an underscore).
- Some documentation updates
- Got rid of the `pve_ceph_repo` variable since it's intended to be something override-able with `pve_ceph_repository_line` anyway.
This is just a note with regards to intensive Ceph testing: I could successfully create loopback devices in the test containers and name them something like `/dev/vdz` (the issue Gaudenz was running into during #52's development was related to reusing the same …
=> A few Ceph-specific updates

README.md, defaults/main.yml, tasks/load_variables.yml, tasks/main.yml, tasks/pve_add_node.yml, tasks/pve_cluster_config.yml, tasks/ssh_cluster_config.yml, vars/main.yml
This collapses all of the address-related variables used for bringing up clusters to `pve_cluster_addr0` and `pve_cluster_addr1`, while maintaining backwards compatibility. The bindnet parameters are no longer passed to `pvecm` either, as they turned out to be redundant to the ring parameters.
This also removes instances in the configuration where the hosts' default IPv4 address was used even if ring0 address was overridden. See #47 for more information.
=> Corosync role variable handling

README.md, defaults/main.yml, tasks/main.yml
I manage my SSH configuration with an [sshd role](https://galaxy.ansible.com/willshersystems/sshd). My particular use case doesn't yet use clustering, so the management of SSH in this module isn't needed. Despite this, the roles go back and forth about the block added by proxmox.
I don't believe these SSH settings are necessary if clustering is disabled, correct?
I've also added a `pve_manage_ssh` (default 'yes'), which would allow someone that uses clustering to still manage their SSH config via a different role. Since this defaults to yes, this won't affect the current behavior when the role is upgraded.
Thanks!
=> Optionally leave SSH config alone

tasks/main.yml
Mira Limbeck stated that this wasn't necessary in current versions of PVE - I went and grepped around and couldn't find any references to it either, so I'm removing it.
https://pve.proxmox.com/pipermail/pve-user/2020-February/171375.html
=> Don't insert pvelocalhost names in /etc/hosts

README.md
- example inventory defines group pve01, not pve
- missing command between dictionary elements
Signed-off-by: Jean-Francois Panisset <panisset@gmail.com>
=> Small README typos

README.md, tasks/ceph.yml
Allows users to specify the crush rule map type for something other than 'host'
=> Allow crush rule 'type' to be overriden to something other than host

README.md, tasks/ceph.yml
It was not possible to create encrypted osds.
This could be neccessary to increase security on hosted servers.
=> added option to create encrypted osds

tasks/main.yml
Unneeded modifications to /etc/hosts and to pvecm are now disabled when pve_cluster_enabled: false.  
Fixes issue #107
=> Expand conditionals when pve_cluster_enabled: false

tasks/main.yml
The ansible `apt_key` module requires gpg to be installed. The gpg package is not present when installing Debian without system tools.
=> Fix trusting Proxmox' packaging key

library/proxmox_acl.py
The `get access/acl` call returns `propagate` as an integer value. However the module was defining it as a string. This resulted in the module constantly redefining the ACL and reporting it as "changed" when nothing was actually changing.
Not sure if at some point in the past this actually was a string, but as of 6.3 it is an integer.
=> change acl "propagate" attribute to integer

README.md
The README is referencing a variable called `pve_clustername` at the first occurrence of clustername, but it should be `pve_cluster_clustername`
=> Fix reference to clustername in README

library/proxmox_storage.py
When you configure a pool with rdb, set username and path is not required.
=> Correct list of required attrs for RBD storages

README.md, tasks/ceph.yml
Ability to manage autoscale mode for pool's Ceph configuration
This Ceph pool uses custom autoscale mode : "off" | "on" | "warn"> (default = "warn")
```
- name: vm-storage,
pgs: 128,
rule: replicated_rule,
application: rbd,
autoscale_mode: "on",
storage: true,
```
=> Add autoscale mode for Ceph pool configuration

README.md, defaults/main.yml, tasks/main.yml
I've configured several servers at different providers to be linked together throw VPN (i'm using Tinc) I that case, my hosts file have to be configured before launching proxmox tasks.
By default, it's change nothing compare to before. If you set the variable to "no", then tasks configuring hosts file are skipped
=> Add the ability to disable hosts file management

README.md, defaults/main.yml, library/collect_kernel_info.py, tasks/ssh_cluster_config.yml
2 fixes for being able to run the role in `--check` mode.
One change switches from generating local files to storing data in variables. The `fetch` module doesn't run in check mode, and while we could change it to force it run in check mode, that alters the state of the local system, which goes against the intent of `--check`. Using a variable allows simplifying the code anyway.
The other change adjusts the `collect_kernel_info` module to always collect data, even in check mode. Otherwise tasks which run in check mode, and depend on the output, would fail.
Fixes #132 
<sup>(re-open of #134. I closed it while checking something, and now github won't let me re-open)</sup>
=> Replace fetch with slurp and identify kernel in check mode

tasks/main.yml
This adds a separate task to define the hosts' names in `/etc/hosts` for a single-node (non-clustered) installation.
Do we also need to define `pvelocalhost` here?
Fixes lae/ansible-role-proxmox#126.
=> Manage /etc/hosts, even when clustering is disabled

tasks/ceph.yml
Install Ceph Monitor daemon only on hosts of the group `pve_ceph_mon_group`
=> Add additional ceph-mon when host in mon group

README.md, defaults/main.yml, tasks/main.yml
Ability to choose on which nodes Ceph is installed.
This is very useful when you want to separate the 'compute nodes' and the 'storage nodes' on Proxmox cluster.
This RP is related to: #130
=> Add ability to specify on wich nodes Ceph is installed

tasks/main.yml
Update to #140.
After attempting to update an existing PVE install with latest develop, I noticed that the hosts file was being modified when it wasn't supposed to be. It turns out that the expression was rendering as follows:
```regex
^\\h*[0-9a-f:.]+
(\\h+.*)*\\h
(pve\.example\.host|pve)
(\\h+.*|\\h*)$
```
This PR updates it so that it renders as follows:
```regex
^\s*[0-9a-f:.]+(\s+.*)*\s (pve\.example\.host|host)(\s+.*|\s*)$
```
Newlines are removed (YAML really is annoying...), the broken escape is fixed and `\h` is replaced with `\s` as after some investigation it doesn't look like Python supports it (refer to `/usr/lib/pythonX.X/sre_parse.py`). The following exception was being thrown:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File …
```
=> Fix regexp match on /etc/hosts for standalone nodes

Vagrantfile, tasks/pve_add_node.yml, tasks/pve_cluster_config.yml, tasks/ssh_cluster_config.yml
This revamps how we manage SSH `known_hosts` files with this role to only modify them during cluster joins. Given that PVE seems to manage this in the first place when a host is clustered (and we didn't touch it on hosts with PVE already installed), I believe this changeset shouldn't break anything and reduces our footprint on hosts.
Closes #138.
=> Ensure hosts with PVE already installed can join clusters

tasks/pve_add_node.yml, tasks/pve_cluster_config.yml
Hello @lae,
First, thank you so much for this role, it is very helpful.
While running a disaster recovery scenario, we identified an issue with the role when we try to reinstall the first node of the cluster.
By default, the initialization node is the first node in the group
`pve_group`. When this node is reinstalled, it is not possible for the
role to wait for quorum on this node since it is not a member of the
cluster yet. Moreover, the tasks in pve_add_node.yml are not run for
this node.
Change the behavior of the role to pick any node already configured in
`pve_cluster_clustername` and use this one as an initialization node.
This does not change the behavior when installing a new cluster.
Without this change:
```
TASK [lae.proxmox : Wait for quorum on initialization node] …
```
=> Fix reinstall of initialization node

README.md, tasks/pve_add_node.yml
Recent changes in `develop` introduced a bug when `pve_manage_ssh: false`.
```
TASK [ansible-role-proxmox : Identify the SSH public key and SSH addresses of initial cluster host] *****************************************
fatal: [pve2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'content'\n\nThe error appears to be in '/home/bruno/.ansible/roles/ansible-role-proxmox/tasks/pve_add_node.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Identify the SSH public key and SSH addresses of initial cluster host\n  ^ here\n"}
fatal: [pve3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The …
```
=> Check for pve_manage_ssh in pve_add_node.yml

library/collect_kernel_info.py
`collect_kernel_info.py` fails to identify the booted kernel when running without GRUB. This changeset updates the module to be bootloader-agnostic. Although I'm not sure if this is a comprehensive enough check...
```
TASK [lae.proxmox : Collect kernel package information] ********************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: subprocess.CalledProcessError: Command '['grep', '-o', '-P', '(?<=BOOT_IMAGE=).*?(?= )', '/proc/cmdline']' returned non-zero exit status 1.
fatal: [internal_host]: FAILED! => {"changed": false, "module_stderr": "Shared connection to internal_host …
```
=> Identify kernel information via /lib/modules instead of boot parameters

tasks/kernel_module_cleanup.yml, tasks/zfs.yml
I noticed my ZFS modprobe configuration was disappearing a while back but wasn't sure how... 😅
I hadn't configured it via this role, but then noticed that it was being removed by the role. So I added a role variable, but it looks like it wasn't actually being configured, since the `bool` here is returning `false` when there's content inside of the role variable. We just want to check if it's not empty, I believe, so I changed it to use `length` instead.
=> Ensure ZFS modprobe configuration is inserted/removed correctly

library/collect_kernel_info.py
This fixes an edge case when there are directories in `/lib/modules` leftover by old packages (possibly, and maybe other reasons).
Failure example:
```
TASK [lae.proxmox : Collect kernel package information] ********************************************************************************************************************************************
fatal: [lilienne.is.also.aikatsu]: FAILED! => {"changed": false, "module_stderr": "Shared connection to lilienne.is.also.aikatsu closed.\r\n", "module_stdout": "\r\ndpkg-query: no path found matching pattern /lib/modules/5.10.0-11-amd64\r\nTraceback (most recent call last):\r\n  File \"/home/lae/.ansible/tmp/ansible-tmp-1646844430.0930457-570959-202055990360712/AnsiballZ_collect_kernel_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n …
```
=> Ignore module dirs that have no associated package

tasks/ceph.yml
The `pve_ceph_volume` and `command` modules do not run in check mode without explicitly setting `check_mode:no`, resulting in failure when running the playbook with `--check`.
=> Make Ceph provisioning work in check mode

tasks/ceph.yml
On a fresh cluster/node with 0 already provisioned OSDs, this will
otherwise fail since _existing_ceph_osds will yield a non-iterable
object.
=> Default to empty list when generating OSD list

library/collect_kernel_info.py
When looking for packages that own a directory in /lib/modules, it returns a comma-delimited list including both header and kernel packages. This properly separates them so that the purge step correctly uninstalls both packages, instead of a nonexistent package.
=> Fix parsing of dpkg-query for old kernel packages

README.md, library/proxmox_storage.py, tasks/main.yml
Closes #163
Possibly some stuff missing, actually. I have some changes for `prune-backups` stashed currently because I need to write more parsing logic around it so I'm putting that off because it seems like it's optional (it's not mentioned in https://pve.proxmox.com/wiki/Storage:_Proxmox_Backup_Server) and applies to storages in general (so I'll work on it separately later). The `encryption-key` JSON might require further validation, but I have no idea what it's supposed to look like.
This isn't being added to the test environment since PVE apparently does try to contact PBS during creation and we obviously can't set up a test PBS instance just for this. However, I think that might only be if it's set to `autogen`? So maybe it'll skip contacting PBS if valid JSON is provided (and thus …
=> Add Proxmox Backup Server storage type

defaults/main.yml
Because ceph-pacific will be EOL on 2023-06-01 the ceph version should be changed.
=> updated default ceph version to quincy

tasks/main.yml, tasks/pve_cluster_config.yml
When the role is run with `--limit nodes_without_first_node`, the HA groups are not configured (tasks are skipped). Use `_init_node` instead of `groups[pve_group][0]` to run the tasks.
`_init_node` is any active node in an already initialized Proxmox cluster which is part of the run.
=> Fix host used to configure HA groups

module_utils/pvesh.py
In Python, only a [limited set of characters][0] can be escaped with a backslash. In recent versions of Python, attempting to escape a non-escapeable character [raises a SyntaxWarning][1], polluting the playbook output with warnings like:
<unknown>:59: SyntaxWarning: invalid escape sequence '\('
<unknown>:60: SyntaxWarning: invalid escape sequence '\.'
<unknown>:61: SyntaxWarning: invalid escape sequence '\.'
This commit adds the string literal prefix 'r' to regular expressions in pvesh.py to ensure that escape sequences are not interpreted in the given strings. As there were no valid escape sequences in those strings to begin with, the actual string content remains the same.
[0]: https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences
[1]: …
=> pvesh: Fix invalid string escape sequences

README.md, defaults/main.yml, tasks/ceph.yml
This filter is deprecated as per https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/ipaddr_filter.html
Use `ansible.utils.ipaddr` instead.
I observed the deprecation notice while adding new nodes to the cluster.
```
TASK [lae.proxmox : Mount Ceph filesystems] ************************************
Friday 31 May 2024  22:09:03 +0000 (0:00:00.299)       0:02:18.056 ************ 
[DEPRECATION WARNING]: Use 'ansible.utils.ipaddr' module instead. This feature 
will be removed from ansible.netcommon in a release after 2024-01-01. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```
=> fix: Replace deprecated ansible.netcommon.ipaddr

README.md, tasks/main.yml
This branch somewhat addresses issue #23 with support for adding non-default authentication domains / realms to `/etc/pve/domains.cfg` in a similar fashion to the way `/etc/pve/datacenter.cfg` is handled. This code overwrites the configuration file directly, it would be preferable if a true Python module were written to use the [domains REST API](https://pve.proxmox.com/pve-docs/api-viewer/#/access/domains/{realm}) but for now this appears to be sufficient to add Active Directory authentication to login to the web UI.
Signed-off-by: Jean-Francois Panisset <panisset@gmail.com>
=> Support for adding authentication realms to domains.cfg

README.md, defaults/main.yml, library/proxmox_storage.py, tasks/main.yml, tasks/pve_add_node.yml, tasks/pve_cluster_config.yml
I added CIFS support and the new feature from pbs for namespaces so that it is possible to mount pbs namespaces with pve_cluster_prio0 and pve_cluster_prio1 it is possible to define which link has the higher priority.
=> Support for CIFS storages, namespacing in PBS, and ranking interfaces for corosync

README.md, defaults/main.yml, library/proxmox_metric_server.py, tasks/main.yml, tests/install.yml
Tested only with PVE 7
Telegraf can be used to transfert metrics to Prometheus, Elasticsearch, etc.
Resolve #259
=> Metric Servers management in Proxmox

.github/workflows/ci.yml, .yamllint.yml
This just runs vagrant with the development `Vagrantfile`, mostly just to provide a sanity check/guideline for PRs, and a start to resolve #166. It should be replaced later to re-use existing test playbooks.
=> Run Vagrant in CI

README.md, defaults/main.yml, tasks/main.yml
=> Allow version pinning of the Proxmox kernel

README.md, tasks/kernel_module_cleanup.yml
=> feature: make watchdog configuration more flexible

tasks/ssh_cluster_config.yml
- Migrates the generated and managed keys to ed25519.
- Manages root authorized_keys exclusively
- Allows additional keys via `pve_ssh_extra_keys`
=> Switch managed ssh keys to ed25519

.github/workflows/amplify.yml
GitHub does not mint OIDC tokens for externally sourced PRs so this workflow can't successfully run on those PRs. An alternative solution (like via an approval comment?) should be identified and implemented eventually to allow the workflow for previous contributors using their own forks.
This also updates the workflow to run on the develop branch.
=> Don't run Amplify on PRs from forks
