lae/ansible-role-proxmox

- .travis.yml
- README.md
- defaults/main.yml
- library/proxmox_query.py
- tasks/kernel_updates.yml
- tasks/main.yml
- tasks/pve_add_node.yml
- tasks/pve_cluster_config.yml
- tasks/ssh_cluster_config.yml
- tests/deploy.yml
- tests/test.yml
- vars/debian-jessie.yml
- vars/debian-stretch.yml
- vars/main.yml
This introduces a `proxmox_query` module to help in the idempotent deployment of a Proxmox cluster. Some other improvements in general are also included.
> Add support for creating clusters

- library/proxmox_query.py
- meta/main.yml
- module_utils/pvesh.py
- tasks/main.yml
- tasks/pve_cluster_config.yml
> Replace proxmoxer dependency with a utility library

- tasks/kernel_updates.yml
> Update wait_for delay to 60s for kernel update reboots

- README.md
- defaults/main.yml
- library/proxmox_storage.py
- tasks/main.yml
- tests/group_vars/all
- tests/test.yml
As asked in #35 , a first attempt to manage storages with this role.
For now, the working type storage are:
- nfs
- dir
- rbd
> Add ability to manage proxmox storage.

- tasks/identify_needed_packages.yml
- tasks/kernel_module_cleanup.yml
- tasks/kernel_updates.yml
- tasks/main.yml
- tasks/zfs.yml
Please have a look. At the moment I didn't test that - because I don't have an idea how to integrate the git repo into my playbook instead of the ansible-galaxy role.
> #57 changed when condition to use bool declaration for boolean variables

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/group_vars/all
- tests/test.yml
Allow configuration of /etc/pve/datacenter.cfg from a dictionary.
> Configuration of datacenter.cfg

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/ceph.yml
- tasks/main.yml
Configuration of Ceph on the Proxmox hosts using pveceph.
> PVE Ceph deployment support

- README.md
- tasks/main.yml
I found some warning again about bool checks within Ansible 2.8 and changed a wrong syntax in my last PR Readme
> Minor fixes

- README.md
- tasks/ceph.yml
As requested, please merge into the feature/ceph-updates (or direct to develop if you want).
> Allow separate Ceph replication network to be defined

- README.md
- tasks/ceph.yml
Added the ability to specify both size and min_size upon creation of ceph pools
> Size parameters for Ceph pools

- .gitignore
- README.md
- defaults/main.yml
- library/proxmox_role.py
- tasks/main.yml
- tests/group_vars/all
This PR adds the option to manage proxmox roles. It is based upon the feature/pve_role branch.
> Added proxmox_role to manage proxmox roles

- .github/FUNDING.yml
- meta/main.yml
- tasks/ceph.yml
- tasks/disable_nmi_watchdog.yml
- tasks/kernel_module_cleanup.yml
- tasks/kernel_updates.yml
- tasks/load_variables.yml
- tasks/main.yml
- tasks/ssl_config.yml
- tasks/zfs.yml
- tests/install.yml
- tests/test.yml
- tests/vagrant/package_role.yml
- tests/vagrant/provision.yml
Made some minor fixes for better YAML syntax
- use | bool filter for unknown var types
- use quotes in when conditions
- correct indentions within blocks
- replace shell script for reboot with existing reboot-module (since Ansible 2.6 available)
> Yaml-Syntax Fixes (Indents, Bool, Reboot-Module)

- README.md
- defaults/main.yml
- tasks/ceph.yml
Ability to configure Ceph nodes as manager
> Add group for deploying multiple Ceph managers

- files/00_remove_checked_command_buster.patch
Update the buster patch for removing the pve subscription nag modal.
Fixes #133
> Fix patch to remove subscription nag

- files/00_remove_checked_command_buster.patch
This patching frequently breaks with updates; I changed this to the smallest possible patch to achieve the same effect.
> Simplify patching of checked_command function

- tasks/ceph.yml
> Add fs mount option

- defaults/main.yml
- library/proxmox_pool.py
- module_utils/pvesh.py
- tasks/main.yml
- tests/vagrant/group_vars/all
Add proxmox pools management.
Pools can use to create spécial path for différent users and fixe needed right directly on pools. 
Pools can containt vm, user, disk, ....
> Add Proxmox pools management

- README.md
- defaults/main.yml
- tasks/load_variables.yml
- vars/main.yml
> Clustering role variable cleanup

- README.md
- library/proxmox_storage.py
> feature: add btrfs as valid storage type

- meta/main.yml
- tasks/ceph.yml
- tasks/main.yml
> Fix minimum host check for clustering

- README.md
> Update Debian codename references in README

- .github/dependabot.yml
- .github/workflows/amplify.yml
- .github/workflows/ci.yml
- **add dependabot configuration for github actions**
- **[actions] bump amplify workflow to v0.2.0**
- **[actions] update CI to only run vagrant if role files are updated**
> CI updates

- tasks/pve_add_node.yml
Fixes #221
...not sure how this branch got lost.
> Specify port in known_hosts when adding cluster nodes.
